---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverservice
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: serverservice
  replicas: 1
  template:
    metadata:
      labels:
        app: serverservice
    spec:
#      securityContext:
#        runAsUser: 1001
#        runAsGroup: 1000
      restartPolicy: Always
      containers:
      - name: serverservice
        image: mastercloudapps/server:v2.23
        securityContext:
          allowPrivilegeEscalation: false
        env:
        # Environment variables for MySQL connection
        - name: QUARKUS_DATASOURCE_DB_KIND
          value: mysql
        - name: QUARKUS_DATASOURCE_JDBC_URL
          value: jdbc:mysql://mysql/eoloplantsDB
        - name: QUARKUS_DATASOURCE_USERNAME
          value: root
        - name: QUARKUS_DATASOURCE_PASSWORD
          value: password
        - name: RABBITMQ_URL
          value: amqp://root:password@rabbitmq
        # Environment variables for RabbitMQ connection
        - name: RABBITMQ_HOST
          value: rabbitmq
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USERNAME
          value: root
        - name: RABBITMQ_PASSWORD
          value: password
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: serverservice
  labels:
    app: serverservice
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: serverservice-port
  selector:
    app: serverservice
  type: ClusterIP