{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ .Values.server.name }}
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.server.name }}
                port:
                  number: 8080
      {{ if .Values.ingress.hostEnabled }}
      host: {{ .Values.ingress.host }}
      {{ end }}
{{ end }}
