{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ .Values.toposervice.name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /{{ .Values.toposervice.name }}/(.+)
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.toposervice.name }}
                port:
                  number: 8181
      {{ if .Values.ingress.hostEnabled }}
      host: {{ .Values.ingress.host }}
      {{ end }}
{{ end }}