toposervice:
  name: toposervice
  image:
    name: mastercloudapps/toposervice
    version: v1.23

weatherservice:
  name: weatherservice
  image:
    name: mastercloudapps/weatherservice
    version: v1.23

server:
  name: serverservice
  image:
    name: mastercloudapps/server
    version: v2.23

planner:
  name: planner
  image:
    name: mastercloudapps/planner
    version: v1.23

mongodb:
  name: mongodb
  image:
    name: mongo
    version: 5.0-focal

mysql:
  name: mysql
  image:
    name: mysql
    version: 8.0

rabbitmq:
  name: rabbitmq
  image:
    name: rabbitmq
    version: 3.11-management

ingress:
  enabled: true
  hostEnabled: false
  host: www.mastercloudapps.com